<?php
/*those define is very important, don't change theme, will affect a lot of themes*/
define('SNEEIT_DEMO_INSTALLER_FOLDER', WP_CONTENT_DIR.'/sneeit-demo');
define('SNEEIT_DEMO_INSTALLER_MEDIA_FILES_FILE_NAME', 'sneeit-demo-media-files');
define('SNEEIT_DEMO_INSTALLER_DATA_FILE_NAME', 'sneeit-demo-data');
define('SNEEIT_DEMO_INSTALLER_MEDIA_STRUCTURE_FILE_NAME', 'sneeit-demo-media-structure');
define('SNEEIT_DEMO_INSTALLER_DOWNLOAD_FILE_NAME', 'sneeit-demo-download');
define('SNEEIT_DEMO_INSTALLER_MAX_FILE_SIZE', 4194304); /* 4MB */
define('SNEEIT_DEMO_INSTALLER_MAX_MOVING_LOOP', 10);
define('SNEEIT_DEMO_INSTALLER_MAX_MOVING_FILE_NUMBER', 100); /*number file to allow moving at a time*/

define('SNEEIT_DEMO_INSTALLER_TABLE_PREFIX_PLACE_HOLDER', '_____SNEEIT_DEMO_INSTALLER_TABLE_PREFIX_PLACE_HOLDER_____');
define('SNEEIT_DEMO_INSTALLER_ADMIN_EMAIL_PLACE_HOLDER', '_____SNEEIT_DEMO_INSTALLER_ADMIN_EMAIL_PLACE_HOLDER____');

define('SNEEIT_DEMO_INSTALLER_UPLOADS_DIR_URL_PLACE_HOLDER', '_____SNEEIT_DEMO_INSTALLER_UPLOADS_DIR_URL_PLACE_HOLDER_____');
define('SNEEIT_DEMO_INSTALLER_THEMES_DIR_URL_PLACE_HOLDER', '_____SNEEIT_DEMO_INSTALLER_THEMES_DIR_URL_PLACE_HOLDER_____');
define('SNEEIT_DEMO_INSTALLER_PLUGINS_DIR_URL_PLACE_HOLDER', '_____SNEEIT_DEMO_INSTALLER_PLUGINS_DIR_URL_PLACE_HOLDER_____');
define('SNEEIT_DEMO_INSTALLER_CONTENT_DIR_URL_PLACE_HOLDER', '_____SNEEIT_DEMO_INSTALLER_CONTENT_DIR_URL_PLACE_HOLDER_____');
define('SNEEIT_DEMO_INSTALLER_INCLUDES_DIR_URL_PLACE_HOLDER', '_____SNEEIT_DEMO_INSTALLER_INCLUDES_DIR_URL_PLACE_HOLDER_____');
define('SNEEIT_DEMO_INSTALLER_ADMIN_DIR_URL_PLACE_HOLDER', '_____SNEEIT_DEMO_INSTALLER_ADMIN_DIR_URL_PLACE_HOLDER_____');
define('SNEEIT_DEMO_INSTALLER_SITE_DIR_URL_PLACE_HOLDER', '_____SNEEIT_DEMO_INSTALLER_SITE_DIR_URL_PLACE_HOLDER_____');
define('SNEEIT_DEMO_INSTALLER_HOME_DIR_URL_PLACE_HOLDER', '_____SNEEIT_DEMO_INSTALLER_HOME_DIR_URL_PLACE_HOLDER_____');
